AWSTemplateFormatVersion: 2010-09-09
Description: Create a Lambda Function from already uploaded code.
Parameters:

# AWS Role that will execute the website updating code.
  LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: 'LambdaExecutionRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: 'Allow'
            Principal:
              Service: 'lambda.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: 'LambdaExecutionPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: 'arn:aws:logs:*:*:*'

  # AWS Lambda function that will use the Lambda execution role to execute the
  # website updating code.
  UpdateWebsiteLambda:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: 'UpdateWebsite'
      Handler: 'lambda_function.lambda_handler'
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: autodeploytest.link-lambda
        S3Key: 'updateWebsiteCode.zip'
      Runtime: 'python3.10'
      MemorySize: 128
      Timeout: 3

Outputs:
  UpdateWebsiteLambdaArn:
    Value: !GetAtt UpdateWebsiteLambda.Arn
    Description: "ARN of the Lambda Function"
